blank_issues_enabled: false
contact_links:
  - name: ${{ github.event.repository.name }} 
    url: "https://tbello.bio/"
    about:  Report issues on the ${{ github.event.repository.name }}  Community